### ISSUE TITLE
Dependencies are case sensitive 

### ISSUE THREAD

**Issue by purepani** [adisbladis/pyproject.nix#17]
When using lib.pep508.parseString, names of packages are returned directly. 
This can cause problems when a package dependency in one place has a different case as another place. As an example, see https://github.com/nix-community/dream2nix/issues/743
Given that the PEP standard is case insensitive, perhaps parseString should return the same value even with 2 differently capitalized values that refer to the same package. I'm unsure whether that makes more sense to put here or elsewhere.

**Comment by adisbladis** [comment]
> Given that the PEP standard is case insensitive

Afaict PEP508 doesn't specify whether names should be normalised or not so I opted not to.
Where normalisation matters you should use https://adisbladis.github.io/pyproject.nix/lib/pypa.html#function-library-lib.pypa.normalizePackageName.
